"""cancelled_at added to sub

Revision ID: 519d5cf4fd95
Revises: fbfba33ad92b
Create Date: 2026-01-22 16:44:22.185792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519d5cf4fd95'
down_revision = 'fbfba33ad92b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('cancelled_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'cancelled_at')
    # ### end Alembic commands ###
