"""initial_schema

Revision ID: 9a48cda69cad
Revises: 
Create Date: 2026-01-27 12:58:16.407410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a48cda69cad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=100), nullable=False),
    sa.Column('eos_date', sa.Date(), nullable=False),
    sa.Column('eol_date', sa.Date(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vendor_model', 'devices', ['vendor', 'model'], unique=False)
    op.create_index('idx_vendor_type', 'devices', ['vendor', 'device_type'], unique=False)
    op.create_index(op.f('ix_devices_device_type'), 'devices', ['device_type'], unique=False)
    op.create_index(op.f('ix_devices_eos_date'), 'devices', ['eos_date'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_slug'), 'devices', ['slug'], unique=True)
    op.create_index(op.f('ix_devices_vendor'), 'devices', ['vendor'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Enum('FREE', 'PRO', name='usertier'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lemonsqueezy_subscription_id', sa.String(), nullable=True),
    sa.Column('lemonsqueezy_customer_id', sa.String(), nullable=True),
    sa.Column('lemonsqueezy_order_id', sa.String(), nullable=True),
    sa.Column('lemonsqueezy_product_id', sa.String(), nullable=True),
    sa.Column('lemonsqueezy_variant_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_lemonsqueezy_subscription_id'), 'subscriptions', ['lemonsqueezy_subscription_id'], unique=True)
    op.create_table('tracked_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_device', 'tracked_devices', ['user_id', 'device_id'], unique=True)
    op.create_index(op.f('ix_tracked_devices_device_id'), 'tracked_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_tracked_devices_id'), 'tracked_devices', ['id'], unique=False)
    op.create_index(op.f('ix_tracked_devices_user_id'), 'tracked_devices', ['user_id'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tracked_device_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('DAYS_365', 'DAYS_180', 'DAYS_90', 'DAYS_30', name='alerttype'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('email_status', sa.Enum('SENT', 'FAILED', name='emailstatus'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_device_id'], ['tracked_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_unique', 'alert_history', ['user_id', 'tracked_device_id', 'alert_type'], unique=True)
    op.create_index(op.f('ix_alert_history_id'), 'alert_history', ['id'], unique=False)
    op.create_index(op.f('ix_alert_history_tracked_device_id'), 'alert_history', ['tracked_device_id'], unique=False)
    op.create_index(op.f('ix_alert_history_user_id'), 'alert_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_history_user_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_tracked_device_id'), table_name='alert_history')
    op.drop_index(op.f('ix_alert_history_id'), table_name='alert_history')
    op.drop_index('idx_alert_unique', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_tracked_devices_user_id'), table_name='tracked_devices')
    op.drop_index(op.f('ix_tracked_devices_id'), table_name='tracked_devices')
    op.drop_index(op.f('ix_tracked_devices_device_id'), table_name='tracked_devices')
    op.drop_index('idx_user_device', table_name='tracked_devices')
    op.drop_table('tracked_devices')
    op.drop_index(op.f('ix_subscriptions_lemonsqueezy_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_devices_vendor'), table_name='devices')
    op.drop_index(op.f('ix_devices_slug'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_eos_date'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_type'), table_name='devices')
    op.drop_index('idx_vendor_type', table_name='devices')
    op.drop_index('idx_vendor_model', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
