"""fix sub

Revision ID: f1fef9b03dca
Revises: 519d5cf4fd95
Create Date: 2026-01-22 19:43:03.502432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1fef9b03dca'
down_revision = '519d5cf4fd95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
