"""plan

Revision ID: fbfba33ad92b
Revises: 001
Create Date: 2026-01-22 16:19:25.333135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbfba33ad92b'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('plan_code', sa.String(length=255), nullable=False))
    op.drop_constraint('subscriptions_user_id_key', 'subscriptions', type_='unique')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_unique_constraint('subscriptions_user_id_key', 'subscriptions', ['user_id'])
    op.drop_column('subscriptions', 'plan_code')
    # ### end Alembic commands ###
